# Generated by Django 4.1 on 2023-02-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingStatus',
        ),
    ]
